"""empty message

Revision ID: 18141423f572
Revises: 4346780f812c
Create Date: 2015-03-24 12:42:58.456659

"""

# revision identifiers, used by Alembic.
revision = '18141423f572'
down_revision = '4346780f812c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('reason_for_joining', sa.Text(), nullable=True),
    sa.Column('favorite_ship', sa.Text(), nullable=True),
    sa.Column('favorite_role', sa.Text(), nullable=True),
    sa.Column('most_fun', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_denied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['last_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_applications')
    ### end Alembic commands ###
