"""empty message

Revision ID: 2181931c90ac
Revises: None
Create Date: 2015-03-13 09:24:03.616036

"""

# revision identifiers, used by Alembic.
revision = '2181931c90ac'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alliances',
    sa.Column('alliance_id', sa.String(length=254), nullable=False),
    sa.Column('alliance_name', sa.String(length=254), nullable=True),
    sa.Column('alliance_ticker', sa.String(length=254), nullable=True),
    sa.Column('executor_corp_id', sa.String(length=254), nullable=True),
    sa.Column('is_blue', sa.Boolean(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('alliance_id'),
    sa.UniqueConstraint('alliance_id')
    )
    op.create_table('api_key_pairs',
    sa.Column('api_id', sa.String(length=254), nullable=False),
    sa.Column('api_key', sa.String(length=254), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('api_id'),
    sa.UniqueConstraint('api_id')
    )
    op.create_table('corporations',
    sa.Column('corporation_id', sa.String(length=254), nullable=False),
    sa.Column('corporation_name', sa.String(length=254), nullable=True),
    sa.Column('corporation_ticker', sa.String(length=254), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_blue', sa.Boolean(), nullable=True),
    sa.Column('alliance_id', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.alliance_id'], ),
    sa.PrimaryKeyConstraint('corporation_id'),
    sa.UniqueConstraint('corporation_id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('characters',
    sa.Column('character_id', sa.String(length=254), nullable=False),
    sa.Column('character_name', sa.String(length=254), nullable=True),
    sa.Column('corporation_id', sa.String(length=254), nullable=True),
    sa.Column('alliance_id', sa.String(length=254), nullable=True),
    sa.Column('api_id', sa.String(length=254), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.alliance_id'], ),
    sa.ForeignKeyConstraint(['api_id'], ['api_key_pairs.api_id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.corporation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('character_id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('hr_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_a_spi', sa.String(length=10), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('corporation_id', sa.String(length=254), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_denied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.corporation_id'], ),
    sa.ForeignKeyConstraint(['last_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_application_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['hr_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('main_character_id', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['main_character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_info')
    op.drop_table('hr_application_comments')
    op.drop_table('hr_applications')
    op.drop_table('characters')
    op.drop_table('roles_users')
    op.drop_table('corporations')
    op.drop_table('api_key_pairs')
    op.drop_table('alliances')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
