"""empty message

Revision ID: 2ef94394fa61
Revises: None
Create Date: 2015-03-12 11:30:18.517990

"""

# revision identifiers, used by Alembic.
revision = '2ef94394fa61'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
