"""empty message

Revision ID: 3830c6540e2a
Revises: 2ef94394fa61
Create Date: 2015-03-13 08:59:08.800745

"""

# revision identifiers, used by Alembic.
revision = '3830c6540e2a'
down_revision = '2ef94394fa61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    ### end Alembic commands ###
