"""empty message

Revision ID: 4346780f812c
Revises: 2181931c90ac
Create Date: 2015-03-24 09:04:14.366352

"""

# revision identifiers, used by Alembic.
revision = '4346780f812c'
down_revision = '2181931c90ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_application_comments')
    op.drop_table('hr_applications')
    op.create_unique_constraint(None, 'alliances', ['alliance_id'])
    op.create_unique_constraint(None, 'api_key_pairs', ['api_id'])
    op.add_column('characters', sa.Column('skillpoints', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'characters', ['character_id'])
    op.create_unique_constraint(None, 'corporations', ['corporation_id'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_constraint(None, 'corporations', type_='unique')
    op.drop_constraint(None, 'characters', type_='unique')
    op.drop_column('characters', 'skillpoints')
    op.drop_constraint(None, 'api_key_pairs', type_='unique')
    op.drop_constraint(None, 'alliances', type_='unique')
    op.create_table('hr_applications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('hr_applications_id_seq'::regclass)"), nullable=False),
    sa.Column('is_a_spi', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('corporation_id', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewer_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_denied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], [u'corporations.corporation_id'], name=u'hr_applications_corporation_id_fkey'),
    sa.ForeignKeyConstraint(['last_user_id'], [u'users.id'], name=u'hr_applications_last_user_id_fkey'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], [u'users.id'], name=u'hr_applications_reviewer_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'hr_applications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'hr_applications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('hr_application_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], [u'hr_applications.id'], name=u'hr_application_comments_application_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'hr_application_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'hr_application_comments_pkey')
    )
    ### end Alembic commands ###
