"""empty message

Revision ID: 4a8bda92a836
Revises: 517eceb82617
Create Date: 2015-03-24 14:46:59.070159

"""

# revision identifiers, used by Alembic.
revision = '4a8bda92a836'
down_revision = '517eceb82617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_applications', sa.Column('main_character_id', sa.String(length=254), nullable=True))
    op.create_foreign_key(None, 'hr_applications', 'characters', ['main_character_id'], ['character_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_applications', type_='foreignkey')
    op.drop_column('hr_applications', 'main_character_id')
    ### end Alembic commands ###
