"""empty message

Revision ID: 517eceb82617
Revises: 18141423f572
Create Date: 2015-03-24 13:09:25.749722

"""

# revision identifiers, used by Alembic.
revision = '517eceb82617'
down_revision = '18141423f572'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_applications', sa.Column('hours', sa.Integer(), nullable=True))
    op.drop_column('hr_applications', 'scale')
    op.drop_column('hr_applications', 'extra')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_applications', sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hr_applications', sa.Column('scale', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('hr_applications', 'hours')
    ### end Alembic commands ###
